### ISSUE TITLE
Error locating network with name default: network default not found

### ISSUE THREAD

**Issue by Dagur** [docker/docker-py#1161]
I had this exact issue with docker-py 1.9
https://github.com/docker/docker-py/issues/714

Looks like this bug has raised its head again.

**Comment by shin-** [comment]
Can you provide more info about the code you're running and what system / docker version you're running on?

**Comment by Dagur** [comment]
Sure. The Docker version is 1.7.1, build 786b29d/1.7.1  (the latest on CentOS 6.8).

I was using docker-py 1.2.2 and got this error after I upgraded it to 1.9 (rolling back to 1.2.2 fixed the problem).

I'm not super familiar with the code but I think this is the relevant bit:

```
host_config = docker.utils.create_host_config(port_bindings={8082: ('0.0.0.0', 59000 + self.id)})
container_id = dc.create_container(
    'company/product:v' + self.version.name,
    ports=[8082],
    name=self.container_name(),
    environment=dict(
        PRODUCT_ENV=settings.PRODUCT_ENV,
        PRODUCT_TENANT_ID=self.id,
        PRODUCT_TENANT=self.slug,
        DATABASE_URL=db_url,
        ELASTIC_URL=el_string,
        PRODUCT_LANGUAGE=self.language.code
    ),
    host_config=host_config
)

dc.start(container_id['Id'])
```

**Comment by Dagur** [comment]
I did some tests again and now everything works fine with 1.9. I'm not sure what happened but I think it's safe to close this. Sorry for wasting your time

**Comment by antoineco** [comment]
@Dagur @shin- I would reopen that, I'm seeing the same thing happening using `docker-py==1.9.0` and `ansible==2.1.1.0` when running the following Ansible task:

```yaml
- name: start containers
  local_action:
    module: docker
    docker_url: tcp://host01.example.com:2375
    docker_api_version: "1.19"
    image: nginx:1.11
    state: reloaded
    pull: always
    name: "nginx-{{ item }}"
    restart_policy: always
  with_sequence: start=1 end=5 format="%02d"
```

```
TASK [ocr : start containers] **********************************************
failed: [host01.example.com -> localhost] (item=01) =>
```
```json
{ "changed": true,
  "failed": true,
  "item": "01",
  "msg": "Docker API Error: Cannot start container 2c3b5d84f6929aa2b9402b7d4711befd76a8c6433613543d9034493015821413: error locating network with name default: network default not found"
}
```

The host is running ``Docker 1.7.1`` (API version 1.19)
It works if I roll back to `docker-py 1.3.1``

--

The code of the Ansible module is here: [docker.py](https://github.com/ansible/ansible-modules-core/blob/stable-2.1/cloud/docker/docker.py#L520)
