### ISSUE TITLE
New 1.10.0 release breaks ansible

### ISSUE THREAD

**Issue by rcoh** [docker/docker-py#1196]
Error:
```{"changed": false, "failed": true, "msg": "Failed to import docker-py - No module named types. Try `pip install docker-py`"}```

**Comment by shin-** [comment]
That's weird. `docker.types` is present and declared in `setup.py`. Installing and importing it in a fresh virtualenv also doesn't seem to raise any issue. Are there more details you can share on what's triggering the issue?

**Comment by rcoh** [comment]
This _should_ reproduce it:
```
- hosts: my_host
  roles:
     - angstwad.docker_ubuntu
- hosts: my_host
  tasks:
    - name: login
      docker_login:
        username: foo
        password: bar
        email: a@a.com 
```
