### ISSUE TITLE
connect_container_to_network() got an unexpected keyword argument 'link_local_ips'"}

### ISSUE THREAD

**Issue by boskiv** [docker/docker-py#1298]
I have ansible playbook with docker task
```
- name: "Running {{ service_name }} thru docker service"
  docker_service:
    project_name: "{{ service_name }}"
    definition:
      version: '2'
      services:
        redis:
          image: redis
          command: redis-server --appendonly yes
          volumes:
            - "/docker-volumes/{{ service_name }}/redis/data:/data"
          restart: always
        service:
          image: "{{ registry_url }}/{{ service_name }}-{{ env }}"
          volumes:
            - "/docker-volumes/{{ service_name }}/{{ conf_target }}:{{ conf_path }}"
          environment:
            EXNESS_APP_SETTINGS: "{{ conf_path }}/config.yml"
            TCP_PORTS: 9000
          links:
            - redis
          depends_on:
            - redis
          restart: always
          logging:
            driver: syslog
            options:
              syslog-address: "{{ syslog_server }}"
              tag: "{{ service_name }}-service-{{ env }}"
        ha:
          image: dockercloud/haproxy
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
          environment:
            - MODE=tcp
            - STATS_PORT=9080
            - OPTION=tcplog
            - RSYSLOG_DESTINATION=logs.exness.io:5000
          ports:
            - "{{ service_ha_port }}:9000"
            - "{{ service_stats_port }}:9080"
          links:
            - service
          depends_on:
            - service
          restart: always
    state: present
    recreate: always
    scale:
      service: "{{ service_scale }}"
  register: output
  when: not celery_only
```

After update to latest docker on server my task failed with message
```
TASK [Running authentication-service thru docker service] **********************
fatal: [docker-host]: FAILED! => {"changed": false, "failed": true, "msg": "Error bring authenticationservice up - connect_container_to_network() got an unexpected keyword argument 'link_local_ips'"}
	to retry, use: --limit @authentication-service.retry
```
```
root@docker-01:/docker-volumes/authentication-service# pip freeze
Landscape-Client==14.12
PAM==0.4.2
PyYAML==3.12
Twisted-Core==13.2.0
apt-xapian-index==0.45
argparse==1.2.1
backports.ssl-match-hostname==3.5.0.1
cached-property==1.3.0
chardet==2.0.1
colorama==0.2.5
configobj==4.7.2
distro-info==0.12
docker-compose==1.9.0
docker-py==1.10.6
docker-pycreds==0.2.1
dockerpty==0.4.1
docopt==0.6.2
enum34==1.1.6
euca2ools==3.0.1
functools32==3.2.3-2
html5lib==0.999
iotop==0.6
ipaddress==1.0.17
jsonschema==2.5.1
lxml==3.3.3
meld3==0.6.10
pyOpenSSL==0.13
pyserial==2.6
python-apt==0.9.3.5ubuntu2
python-debian==0.1.21-nmu2ubuntu2
requestbuilder==0.1.0-beta1
requests==2.12.1
six==1.10.0
ssh-import-id==3.21
supervisor==3.0b2
texttable==0.8.7
urllib3==1.7.1
websocket-client==0.37.0
wheel==0.24.0
wsgiref==0.1.2
zope.interface==4.0.5
```

ansible==2.1.0.0
