### ISSUE TITLE
IPv6 port binding error with docker composer

### ISSUE THREAD

**Issue by LennardWesterveld** [docker/docker-py#1361]
Hi,

There is a issue by using IPv6 by port/publishing in docker-compose file see for more info also:[#2663](https://github.com/docker/compose/issues/2663)

How reproduce:
1. Create docker-compose with for example:
```
version: '2.1'

services:
  web:
    image: 'tutum/hello-world'
    ports:
      - '[2a01:7c8:fffb:31::1]:80:80'
```
2. docker-compose up
And you get the follow error:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.web.ports is invalid: Invalid port "[2a01:7c8:fffb:31::1]:80:80", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
```

Version information:
```
docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```
