### ISSUE TITLE
Publish service port in host mode

### ISSUE THREAD

**Issue by greenmaid** [docker/docker-py#1878]
Hello,

I'm trying to create a service publishing a port in host mode with the Python SDK, but i don't see option to do so :(

It is possible via docker command line (https://docs.docker.com/engine/reference/commandline/service_create/#options) : 
`docker service create -p mode=host,published=80,target=80 --name test httpd`

It is also possible via docker-compose:
````
services:
  test:
    image: httpd
    ports:
      - mode: host
        target: 80
        published: 80
    deploy:
      mode: replicated
      replicas: 1
````

Is there a way to achieve the same result via python SDK ?

Thanks !
