### ISSUE TITLE
Compatible version of docker registry with docker-py 1.2.1 ? 

### ISSUE THREAD

**Issue by akkumar** [docker/docker-py#1999]
I am working on a piece of code to have a docker py client (3.2.1) client communicate with another docker registry container. 

( See: https://github.com/docker/distribution/blob/master/docs/spec/api.md )

My docker registry definition ( in docker-compose ) looks as below
```yml
services:
  docker_registry:
    image: "registry:2.6.2"
    restart: "always"
    ports:
      - "127.0.0.1:15000:5000"
    environment:
      STORAGE_PATH: "/opt/docker_registry/v09"
```
when my docker client communicates with the server - I am getting the following:

```console
requests.exceptions.HTTPError: 404 Client Error: : Not Found for url: http://docker_registry:5000/v1.35/build?t=my-build%3A1.0.0&q=False&nocache=True&rm=False&forcerm=True&pull=False&buildargs=..
```
My docker client instantiation code looks as

```python
self.client = docker.DockerClient(base_url=tcp://docker_registry:5000)
```
I do see DockerClient takes in a 'version' as argument.  And the docs mention that it is auto-inferred from the server anyway.

What is the version of docker library/registry , ( https://hub.docker.com/r/library/registry/tags/ ) that would be compatible with docker py client 3.2.1 , so I can run the docker library/registry as a registry service for docker py to communicate successfully ?

Is there a specific version that I need to provide to DockerClient to make it work explicitly ? 

Looking forward to suggestions regarding the same
