### ISSUE TITLE
depends_on 

### ISSUE THREAD

**Issue by saulomeirelles** [docker/docker-py#3074]
Hi everyone,

I am not too familiar with `docker-py` and am trying to translate the following `docker-compose.yml` into Python. 

````yml
version: "3"
services:
  xbeach-vis:
    image: deltares/docker-visualization-xbeach
    depends_on:
      - xbeach-run
    ports:
      - "8888:8888"
  xbeach-run:
    image: deltares/xbeach
    volumes:
      - ./:/data
    command: mmi-runner xbeach params.txt --port 53606
````

I have created a container for each of the services but can't figure out how to express the dependency between `xbeach-viz` and `xbeach-run`.

My question is: how can I set the dependency on the `xbeach-run` service as the parameter `depends_on`  is not in [client.containers](https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.run)?

Thanks, Saulo
